In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as smp
import seaborn as sns
import scipy as sp
from scipy.misc import derivative
from sympy import integrate

In [2]:
x,a,b,c = smp.symbols('x a b c', real= True)
f= x*smp.exp(a*smp.sin(x*b**3))*smp.log(c*smp.log(x**2))
f

x*exp(a*sin(b**3*x))*log(c*log(x**2))

In [3]:
dfdx= smp.diff(f,x)
dfdx

a*b**3*x*exp(a*sin(b**3*x))*log(c*log(x**2))*cos(b**3*x) + exp(a*sin(b**3*x))*log(c*log(x**2)) + 2*exp(a*sin(b**3*x))/log(x**2)

In [4]:
d4fdx4 = smp.diff(f,x,4)
d4fdx4

(a*b**12*x*(a**3*cos(b**3*x)**4 - 6*a**2*sin(b**3*x)*cos(b**3*x)**2 + 3*a*sin(b**3*x)**2 - 4*a*cos(b**3*x)**2 + sin(b**3*x))*log(c*log(x**2)) - 4*a*b**9*(-a**2*cos(b**3*x)**2 + 3*a*sin(b**3*x) + 1)*log(c*log(x**2))*cos(b**3*x) - 8*a*b**9*(-a**2*cos(b**3*x)**2 + 3*a*sin(b**3*x) + 1)*cos(b**3*x)/log(x**2) - 12*a*b**6*(1 + 2/log(x**2))*(a*cos(b**3*x)**2 - sin(b**3*x))/(x*log(x**2)) + 24*a*b**6*(a*cos(b**3*x)**2 - sin(b**3*x))/(x*log(x**2)) - 24*a*b**3*(1 + 2/log(x**2))*cos(b**3*x)/(x**2*log(x**2)) + 16*a*b**3*(1 + 3/log(x**2) + 4/log(x**2)**2)*cos(b**3*x)/(x**2*log(x**2)) + 16*(1 + 3/log(x**2) + 4/log(x**2)**2)/(x**3*log(x**2)) - 4*(3 + 11/log(x**2) + 24/log(x**2)**2 + 24/log(x**2)**3)/(x**3*log(x**2)))*exp(a*sin(b**3*x))

In [5]:
x1,a,b = smp.symbols('x1 a b ', real= True)
g= b*x*smp.exp(a*(x1)**2)
Ing= smp.integrate(g,x1)
Ing

b*x*Piecewise((sqrt(pi)*erf(x1*sqrt(-a))/(2*sqrt(-a)), Ne(a, 0)), (x1, True))

In [6]:
x,y,z,u1,u2,u3,v1,v2,v3,t = smp.symbols('x y z u_1 u_2 u_3 v_1 v_2 v_3 t')

In [7]:
a= np.array([1,2,3])
b= np.array([7,8,9])
u= smp.Matrix([u1,u2,u3])
v=smp.Matrix([v1,v2,v3])

In [8]:
from sympy.vector import *
from scipy.integrate import quad
from scipy.integrate import quad_vec

In [9]:
2*a+b

array([ 9, 12, 15])

In [10]:
2*u+v

Matrix([
[2*u_1 + v_1],
[2*u_2 + v_2],
[2*u_3 + v_3]])

In [11]:
np.dot(a,b)

50

In [12]:
u.dot(v)

u_1*v_1 + u_2*v_2 + u_3*v_3

In [13]:
np.cross(a,b)

array([-6, 12, -6])

In [14]:
u.cross(v)

Matrix([
[ u_2*v_3 - u_3*v_2],
[-u_1*v_3 + u_3*v_1],
[ u_1*v_2 - u_2*v_1]])

In [15]:
np.linalg.norm(a)

3.7416573867739413

In [16]:
u.norm()

sqrt(Abs(u_1)**2 + Abs(u_2)**2 + Abs(u_3)**2)

Vector Projection

In [17]:
proj_b_a= np.dot(a,b)/np.linalg.norm(b)**2*b

proj_b_a

array([1.80412371, 2.06185567, 2.31958763])

In [18]:
proj_u_v= u.dot(v)/v.norm()**2*v

proj_u_v

Matrix([
[v_1*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)],
[v_2*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)],
[v_3*(u_1*v_1 + u_2*v_2 + u_3*v_3)/(Abs(v_1)**2 + Abs(v_2)**2 + Abs(v_3)**2)]])

Lines/ Planes