In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import tree

# Data source is from: https://drive.google.com/drive/folders/15lSrc4176J9z9_3WZo_b91BaNfItc2s0
# By Machine Learning With Python Full Course 2023 | Machine Learning Tutorial for Beginners| Simplilearn

In [ ]:
file_path= '/content/Decision_Tree_ Dataset.csv'
cols= ['Initial_Payment', 'Last_Payment', 'Credit_Score','House_Number', 'Sum', 'Result']
df= pd.read_csv(file_path, names=cols)

In [ ]:
df= df.drop(0)
df= df.drop('Sum', axis= 1)
df.head()

Initial_Payment  Last_Payment  Credit_Score  House_Number Result
1              201         10018           250          3046    yes
2              205         10016           395          3044    yes
3              257         10129           109          3251    yes
4              246         10064           324          3137    yes
5              117         10115           496          3094    yes

In [ ]:

mod_df= df.convert_dtypes(float)
print(mod_df.describe())
print(mod_df.info())

       Initial_Payment  Last_Payment  Credit_Score  House_Number
count           1000.0        1000.0        1000.0        1000.0
mean           294.343     12465.884       528.042      4027.011
std          115.81539    1440.15617    259.796059    565.164179
min              100.0       10005.0         100.0        3003.0
25%              195.0       11201.5         302.0        3545.0
50%              289.5       12450.0         516.5        4041.5
75%              398.0      13678.25         753.5        4507.0
max              500.0       14996.0         997.0        5000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 1 to 1000
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Initial_Payment  1000 non-null   Int64 
 1   Last_Payment     1000 non-null   Int64 
 2   Credit_Score     1000 non-null   Int64 
 3   House_Number     1000 non-null   Int64 
 4   Result           1000 non-null   s

Train, Test, Splitting data up

In [ ]:
## creating feature dataset and target dataset
## x = features y= target
X= mod_df.values[:, 0:4]
y= mod_df.values[:, -1]
## Splitting up the data now
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=.3, random_state=100)
clf_entropy= DecisionTreeClassifier(criterion='entropy', random_state=100,
max_depth=3, min_samples_leaf= 5)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)

In [ ]:
y_pred= clf_entropy.predict(X_test)
y_pred

array(['yes', 'yes', 'No', 'yes', 'No', 'yes', 'yes', 'yes', 'No', 'No',
       'No', 'No', 'yes', 'No', 'No', 'yes', 'yes', 'No', 'yes', 'No',
       'No', 'yes', 'No', 'yes', 'yes', 'No', 'No', 'yes', 'No', 'No',
       'No', 'yes', 'yes', 'yes', 'yes', 'No', 'No', 'No', 'yes', 'No',
       'yes', 'yes', 'yes', 'No', 'No', 'yes', 'yes', 'yes', 'No', 'No',
       'yes', 'No', 'yes', 'yes', 'yes', 'yes', 'No', 'yes', 'No', 'yes',
       'yes', 'No', 'yes', 'yes', 'No', 'yes', 'yes', 'yes', 'No', 'No',
       'No', 'No', 'No', 'yes', 'No', 'yes', 'yes', 'No', 'yes', 'No',
       'No', 'No', 'No', 'yes', 'No', 'yes', 'No', 'yes', 'yes', 'No',
       'yes', 'yes', 'yes', 'yes', 'yes', 'No', 'yes', 'yes', 'yes',
       'yes', 'No', 'No', 'yes', 'yes', 'No', 'yes', 'yes', 'yes', 'No',
       'yes', 'yes', 'yes', 'yes', 'No', 'No', 'yes', 'yes', 'yes', 'No',
       'No', 'No', 'No', 'yes', 'yes', 'No', 'yes', 'yes', 'yes', 'No',
       'No', 'yes', 'yes', 'No', 'yes', 'yes', 'yes', 'No', 'ye

In [ ]:
print(f'Accuracy is {accuracy_score(y_pred, y_test)*100}')

Accuracy is 93.66666666666667


In [ ]:
report= classification_report(y_pred, y_test)
print(report)

              precision    recall  f1-score   support

          No       0.91      0.96      0.93       140
         yes       0.96      0.92      0.94       160

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300



In [ ]:
report_matrix= confusion_matrix(y_pred,y_test)
print(report_matrix)

[[134   6]
 [ 13 147]]


Random Forest Implantation

In [ ]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
np.random.seed(0)

In [ ]:
iris= load_iris()
dataset= pd.DataFrame(iris.data, columns= iris.feature_names)
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
dataset['species']= pd.Categorical.from_codes(iris.target, iris.target_names)
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [ ]:
dataset['is_train']= np.random.uniform(0,1,len(dataset)) <=.75
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa     False  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [ ]:
train, test= dataset[dataset['is_train']==True], dataset[dataset['is_train']==False]
print(f'Number of observations of Training Data {len(train)}')
print(f'Number of observations of Testing Data {len(test)}')

Number of observations of Training Data 112
Number of observations of Testing Data 38


In [ ]:
features= dataset.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [ ]:
y=pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
clf= RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [ ]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
clf.predict_proba(test[features])[10:20]

array([[0.  , 0.89, 0.11],
       [0.  , 0.94, 0.06],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 0.98, 0.02],
       [0.  , 0.23, 0.77]])

In [ ]:
preds= iris.target_names[clf.predict(test[features])]
preds[0:25]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica'], dtype='<U10')

In [ ]:
test['species'].head()

1     setosa
5     setosa
6     setosa
13    setosa
14    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [ ]:
pd.crosstab(test['species'], preds, rownames= ['Actual Species'], colnames= ['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 10           0          0
versicolor              0           9          0
virginica               0           0         19

Random Forest Model predicts 100%-- really rare.

In [ ]:
## Note
## Let x be some array with flower data.
preds= iris.target_names[clf.predict([x])]
## this would predict an array of flower data and classify them as the three of following flowers
## setosa , versicolor, virginica